  
# 核心任务
- name: ELK
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  roles:
    - {role: role_common, tags: "role_common"}  
    - {role: role_jdk, tags: "role_jdk"}  
    - {role: role_elasticsearch, tags: "role_elasticsearch"}
    - {role: role_logstash, tags: "role_logstash"}
    - {role: role_kibana, tags: "role_kibana"}
    - {role: role_preend, tags: "role_preend"}
    - {role: role_end, tags: "role_end"}
